const LANG = {
    login_title: "Login",
    username_placeholder: "Username",
    password_placeholder: "Password",
    login_btn: "Login",
    logout_btn: "Logout",
    boss_schedule_title: "L9 Galaxy Field Boss Schedule",
    respawn: "Respawn",
    pick_datetime: "Pick Date & Time",
    kill: "Kill",
    unkill: "Unkill",
    alive: "Alive",
    dead: "Dead",
    cancel: "Cancel",
    confirm: "Confirm",
    time: "Time:",
    no_date: "No date selected",
    add_boss: "Add Boss",
    edit_boss: "Edit Boss",
    boss_name: "Boss Name",
    location: "Location",
    level: "Level",
    schedule_type: "Schedule Type",
    choose_schedule: "Choose schedule type",
    weekly_schedule: "Weekly Schedule",
    hourly_respawn: "Hourly Respawn",
    respawn_duration: "Respawn Duration",
    days: "Days",
    hours: "Hours",
    minutes: "Minutes",
    boss_image: "Boss Image",
    max_size: "Max 4MB",
    save: "Save",
    delete: "Delete",
    confirm_delete: "Are you sure you want to delete this boss? This action cannot be undone.",
    sort_default: "Sort: Default",
    sort_level: "Sort: Level",
    sort_respawn: "Sort: Respawn Time",
    day: "Day",
    hour: "Hour",
    min: "Min",
    add_time: "Add Time",
    no_times_set: "No times set",
    select_day: "Select day",
    name_required: "Name is required",
    location_required: "Location is required",
    level_required: "Level is required",
    schedule_required: "Schedule Type is required",
    respawn_required: "Respawn duration must be greater than 0",
    duplicate_boss: "Boss already exists",
    save_failed: "Failed to save boss",
    delete_failed: "Failed to delete boss",
    image_too_large: "Image must be 4MB or smaller",
    login_failed: "Login failed: Username and password do not match",
    config_error: "Error loading configuration",
    discord_settings: "Discord Settings",
    discord_notifications: "Discord Notifications",
    enable_discord: "Enable Discord Notifications",
    webhook_url: "Discord Webhook URL",
    webhook_hint: "Get webhook from Discord Server Settings → Integrations",
    role_id: "Discord Role ID (optional)",
    role_hint: "Right-click role in Discord → Copy ID (enable Developer Mode)",
    notify_before: "Notify before respawn (minutes)",
    test_webhook: "Test Webhook",
    settings_saved: "Settings saved successfully!"
};
