const LANG = {
    en: {
        login_title: "Login",
        username_placeholder: "Username",
        password_placeholder: "Password",
        login_btn: "Login",
        logout_btn: "Logout",
        boss_schedule_title: "L9 Galaxy Field Boss Schedule",
        respawn: "Respawn",
        pick_datetime: "Pick Date & Time",
        kill: "Kill",
        unkill: "Unkill",
        alive: "Alive",
        dead: "Dead",
        cancel: "Cancel",
        confirm: "Confirm",
        time: "Time:",
        no_date: "No date selected",
        add_boss: "Add Boss",
        edit_boss: "Edit Boss",
        boss_name: "Boss Name",
        location: "Location",
        level: "Level",
        schedule_type: "Schedule Type",
        choose_schedule: "Choose schedule type",
        weekly_schedule: "Weekly Schedule",
        hourly_respawn: "Hourly Respawn",
        respawn_duration: "Respawn Duration",
        days: "Days",
        hours: "Hours",
        minutes: "Minutes",
        boss_image: "Boss Image",
        max_size: "Max 4MB",
        save: "Save",
        delete: "Delete",
        confirm_delete: "Are you sure you want to delete this boss? This action cannot be undone.",
        sort_default: "Sort: Default",
        sort_level: "Sort: Level",
        sort_respawn: "Sort: Respawn Time",
        day: "Day",
        hour: "Hour",
        min: "Min",
        add_time: "Add Time",
        no_times_set: "No times set",
        select_day: "Select day",
        name_required: "Name is required",
        location_required: "Location is required",
        level_required: "Level is required",
        schedule_required: "Schedule Type is required",
        respawn_required: "Respawn duration must be greater than 0",
        duplicate_boss: "Boss already exists",
        save_failed: "Failed to save boss",
        delete_failed: "Failed to delete boss",
        image_too_large: "Image must be 4MB or smaller",
        login_failed: "Login failed: Username and password do not match",
        config_error: "Error loading configuration",
        discord_settings: "Discord Settings",
        discord_notifications: "Discord Notifications",
        enable_discord: "Enable Discord Notifications",
        webhook_url: "Discord Webhook URL",
        webhook_hint: "Get webhook from Discord Server Settings → Integrations",
        role_id: "Discord Role ID (optional)",
        role_hint: "Right-click role in Discord → Copy ID (enable Developer Mode)",
        notify_before: "Notify before respawn (minutes)",
        test_webhook: "Test Webhook",
        settings_saved: "Settings saved successfully!"
    },
    th: {
        login_title: "เข้าสู่ระบบ",
        username_placeholder: "ชื่อผู้ใช้",
        password_placeholder: "รหัสผ่าน",
        login_btn: "เข้าสู่ระบบ",
        logout_btn: "ออกจากระบบ",
        boss_schedule_title: "ตารางบอสแ GALAXY L9",
        respawn: "เกิดใหม่",
        pick_datetime: "เลือกวันและเวลา",
        kill: "ฆ่า",
        unkill: "คืนสถานะ",
        alive: "มีชีวิต",
        dead: "ตาย",
        cancel: "ยกเลิก",
        confirm: "ยืนยัน",
        time: "เวลา:",
        no_date: "ยังไม่ได้เลือกวันที่",
        add_boss: "เพิ่มบอส",
        edit_boss: "แก้ไขบอส",
        boss_name: "ชื่อบอส",
        location: "สถานที่",
        level: "ระดับ",
        schedule_type: "ประเภทการเกิด",
        choose_schedule: "เลือกประเภทการเกิด",
        weekly_schedule: "ตารางรายสัปดาห์",
        hourly_respawn: "เกิดตามชั่วโมง",
        respawn_duration: "ระยะเวลาเกิดใหม่",
        days: "วัน",
        hours: "ชั่วโมง",
        minutes: "นาที",
        boss_image: "รูปภาพบอส",
        max_size: "ขนาดไม่เกิน 4MB",
        save: "บันทึก",
        delete: "ลบ",
        confirm_delete: "คุณแน่ใจหรือไม่ที่จะลบบอสนี้? การกระทำนี้ไม่สามารถยกเลิกได้",
        sort_default: "เรียง: ค่าเริ่มต้น",
        sort_level: "เรียง: ระดับ",
        sort_respawn: "เรียง: เวลาเกิด",
        day: "วัน",
        hour: "ชั่วโมง",
        min: "นาที",
        add_time: "เพิ่มเวลา",
        no_times_set: "ยังไม่มีเวลา",
        select_day: "เลือกวัน",
        name_required: "กรุณากรอกชื่อบอส",
        location_required: "กรุณากรอกสถานที่",
        level_required: "กรุณากรอกระดับ",
        schedule_required: "กรุณาเลือกประเภทการเกิด",
        respawn_required: "ระยะเวลาเกิดใหม่ต้องมากกว่า 0",
        duplicate_boss: "บอสนี้มีอยู่แล้ว",
        save_failed: "ไม่สามารถบันทึกบอสได้",
        delete_failed: "ไม่สามารถลบบอสได้",
        image_too_large: "รูปภาพต้องมีขนาดไม่เกิน 4MB",
        login_failed: "เข้าสู่ระบบล้มเหลว: ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง",
        config_error: "เกิดข้อผิดพลาดในการโหลดการตั้งค่า",
        discord_settings: "การตั้งค่า Discord",
        discord_notifications: "การแจ้งเตือน Discord",
        enable_discord: "เปิดใช้งานการแจ้งเตือน Discord",
        webhook_url: "URL Webhook ของ Discord",
        webhook_hint: "รับ Webhook จาก Discord Server Settings → Integrations",
        role_id: "ID บทบาท Discord (ไม่บังคับ)",
        role_hint: "คลิกขวาบทบาทใน Discord → คัดลอก ID (เปิด Developer Mode)",
        notify_before: "แจ้งเตือนก่อนเกิด (นาที)",
        test_webhook: "ทดสอบ Webhook",
        settings_saved: "บันทึกการตั้งค่าสำเร็จ!"
    }
};
