const LANG = {
    en: {
        login_title: "Login",
        username_placeholder: "Username",
        password_placeholder: "Password",
        login_btn: "Login",
        logout_btn: "Logout",
        boss_schedule_title: "L9 Galaxy Field Boss Schedule",
        respawn: "Respawn",
        pick_datetime: "Pick Date & Time",
        kill: "Kill",
        unkill: "Unkill",
        alive: "Alive",
        dead: "Dead",
        cancel: "Cancel",
        confirm: "Confirm",
        time: "Time:",
        no_date: "No date selected",
        add_boss: "Add Boss",
        edit_boss: "Edit",
        delete_boss: "Delete",
        save: "Save",
        name: "Name",
        location: "Location",
        level: "Level",
        respawn_time: "Respawn Time",
        image: "Image",
        add_new_boss_title: "Add New Boss",
        edit_boss_title: "Edit Boss",
        image_size_error: "Image must be less than 4MB",
        boss_added: "Boss added successfully",
        boss_updated: "Boss updated successfully",
        boss_deleted: "Boss deleted successfully",
        error: "Error",
        success: "Success"
    },
    th: {
        login_title: "เข้าสู่ระบบ",
        username_placeholder: "ชื่อผู้ใช้",
        password_placeholder: "รหัสผ่าน",
        login_btn: "เข้าสู่ระบบ",
        logout_btn: "ออกจากระบบ",
        boss_schedule_title: "ตารางบอส",
        respawn: "เกิดใหม่",
        pick_datetime: "เลือกวันและเวลา",
        kill: "ฆ่า",
        unkill: "คืนสถานะ",
        alive: "มีชีวิต",
        dead: "ตาย",
        cancel: "ยกเลิก",
        confirm: "ยืนยัน",
        time: "เวลา:",
        no_date: "ยังไม่ได้เลือกวันที่",
        add_boss: "เพิ่มบอส",
        edit_boss: "แก้ไข",
        delete_boss: "ลบ",
        save: "บันทึก",
        name: "ชื่อ",
        location: "สถานที่",
        level: "เลเวล",
        respawn_time: "เวลาเกิดใหม่",
        image: "รูปภาพ",
        add_new_boss_title: "เพิ่มบอสใหม่",
        edit_boss_title: "แก้ไขบอส",
        image_size_error: "รูปภาพต้องน้อยกว่า 4MB",
        boss_added: "เพิ่มบอสเรียบร้อย",
        boss_updated: "อัปเดตบอสเรียบร้อย",
        boss_deleted: "ลบบอสเรียบร้อย",
        error: "ข้อผิดพลาด",
        success: "สำเร็จ"
    }
};
